# Small Selected Alt Experiment

Kontrolowany test malej liczby cech na istniejacym `session_aligned` dataset:
- `price_only`
- `price_plus_google_small`
- `price_plus_reddit_small`
- `price_plus_google_reddit_small`

Cel: sprawdzic, czy problemem byl glownie nadmiar cech i overfitting.

In [2]:
from small_selected_alt_experiment import run_small_selected_alt_experiment

result = run_small_selected_alt_experiment()
result["metrics"].query("split == 'test'").sort_values(["ticker", "model_name", "feature_set"]).reset_index(drop=True)

,ticker,model_name,feature_set,split,n_rows,n_features,train_rows_per_feature,accuracy,balanced_accuracy,f1,roc_auc
0,AAPL,hist_gradient_boosting,price_only,test,128,14,44.500000,0.546875,0.533990,0.618421,0.552709
1,AAPL,hist_gradient_boosting,price_plus_google_reddit_small,test,128,24,25.958333,0.546875,0.542857,0.585714,0.553695
2,AAPL,hist_gradient_boosting,price_plus_google_small,test,128,17,36.647059,0.539062,0.528325,0.604027,0.536946
3,AAPL,hist_gradient_boosting,price_plus_reddit_small,test,128,21,29.666667,0.531250,0.525616,0.577465,0.583990
4,AAPL,logreg,price_only,test,128,14,44.500000,0.507812,0.511576,0.511628,0.497044
5,AAPL,logreg,price_plus_google_reddit_small,test,128,24,25.958333,0.523438,0.524384,0.541353,0.551232
6,AAPL,logreg,price_plus_google_small,test,128,17,36.647059,0.500000,0.500000,0.522388,0.510591
7,AAPL,logreg,price_plus_reddit_small,test,128,21,29.666667,0.500000,0.502956,0.507692,0.553448
8,AAPL,random_forest,price_only,test,128,14,44.500000,0.507812,0.505665,0.540146,0.538177
9,AAPL,random_forest,price_plus_google_reddit_small,test,128,24,25.958333,0.562500,0.563054,0.582090,0.572906
10,AAPL,random_forest,price_plus_google_small,test,128,17,36.647059,0.531250,0.531527,0.552239,0.547291
11,AAPL,random_forest,price_plus_reddit_small,test,128,21,29.666667,0.562500,0.560099,0.594203,0.614286
12,ALL,hist_gradient_boosting,price_only,test,256,14,NaN,0.562500,0.558569,0.600000,0.556232
13,ALL,hist_gradient_boosting,price_plus_google_reddit_small,test,256,24,NaN,0.554688,0.556109,0.568182,0.573449
14,ALL,hist_gradient_boosting,price_plus_google_small,test,256,17,NaN,0.535156,0.531360,0.573477,0.547562
15,ALL,hist_gradient_boosting,price_plus_reddit_small,test,256,21,NaN,0.562500,0.559245,0.597122,0.600873
16,ALL,logreg,price_only,test,256,14,NaN,0.554688,0.560844,0.544000,0.559860
17,ALL,logreg,price_plus_google_reddit_small,test,256,24,NaN,0.570312,0.573203,0.576923,0.585316
18,ALL,logreg,price_plus_google_small,test,256,17,NaN,0.546875,0.549591,0.553846,0.565886
19,ALL,logreg,price_plus_reddit_small,test,256,21,NaN,0.527344,0.530929,0.529183,0.570866
20,ALL,random_forest,price_only,test,256,14,NaN,0.562500,0.566009,0.565891,0.579413
21,ALL,random_forest,price_plus_google_reddit_small,test,256,24,NaN,0.566406,0.570282,0.568093,0.584087
22,ALL,random_forest,price_plus_google_small,test,256,17,NaN,0.539062,0.542397,0.542636,0.569760
23,ALL,random_forest,price_plus_reddit_small,test,256,21,NaN,0.578125,0.579721,0.590909,0.618152
24,TSLA,hist_gradient_boosting,price_only,test,128,14,44.500000,0.578125,0.581675,0.578125,0.569885
25,TSLA,hist_gradient_boosting,price_plus_google_reddit_small,test,128,24,25.958333,0.562500,0.568411,0.548387,0.600590
26,TSLA,hist_gradient_boosting,price_plus_google_small,test,128,17,36.647059,0.531250,0.533284,0.538462,0.565954
27,TSLA,hist_gradient_boosting,price_plus_reddit_small,test,128,21,29.666667,0.593750,0.592483,0.617647,0.622451
28,TSLA,logreg,price_only,test,128,14,44.500000,0.601562,0.609555,0.578512,0.618767
29,TSLA,logreg,price_plus_google_reddit_small,test,128,24,25.958333,0.617188,0.621592,0.614173,0.598870
30,TSLA,logreg,price_plus_google_small,test,128,17,36.647059,0.593750,0.598624,0.587302,0.612626
31,TSLA,logreg,price_plus_reddit_small,test,128,21,29.666667,0.554688,0.558708,0.551181,0.577745
32,TSLA,random_forest,price_only,test,128,14,44.500000,0.617188,0.625276,0.595041,0.611152
33,TSLA,random_forest,price_plus_google_reddit_small,test,128,24,25.958333,0.570312,0.576885,0.552846,0.599853
34,TSLA,random_forest,price_plus_google_small,test,128,17,36.647059,0.546875,0.552690,0.532258,0.590518
35,TSLA,random_forest,price_plus_reddit_small,test,128,21,29.666667,0.593750,0.598624,0.587302,0.628347

,ticker,model_name,feature_set,split,n_rows,n_features,train_rows_per_feature,accuracy,balanced_accuracy,f1,roc_auc
0,AAPL,hist_gradient_boosting,price_only,test,128,14,44.500000,0.546875,0.533990,0.618421,0.552709
1,AAPL,hist_gradient_boosting,price_plus_google_reddit_small,test,128,24,25.958333,0.546875,0.542857,0.585714,0.553695
2,AAPL,hist_gradient_boosting,price_plus_google_small,test,128,17,36.647059,0.539062,0.528325,0.604027,0.536946
3,AAPL,hist_gradient_boosting,price_plus_reddit_small,test,128,21,29.666667,0.531250,0.525616,0.577465,0.583990
4,AAPL,logreg,price_only,test,128,14,44.500000,0.507812,0.511576,0.511628,0.497044
5,AAPL,logreg,price_plus_google_reddit_small,test,128,24,25.958333,0.523438,0.524384,0.541353,0.551232
6,AAPL,logreg,price_plus_google_small,test,128,17,36.647059,0.500000,0.500000,0.522388,0.510591
7,AAPL,logreg,price_plus_reddit_small,test,128,21,29.666667,0.500000,0.502956,0.507692,0.553448
8,AAPL,random_forest,price_only,test,128,14,44.500000,0.507812,0.505665,0.540146,0.538177
9,AAPL,random_forest,price_plus_google_reddit_small,test,128,24,25.958333,0.562500,0.563054,0.582090,0.572906
10,AAPL,random_forest,price_plus_google_small,test,128,17,36.647059,0.531250,0.531527,0.552239,0.547291
11,AAPL,random_forest,price_plus_reddit_small,test,128,21,29.666667,0.562500,0.560099,0.594203,0.614286
12,ALL,hist_gradient_boosting,price_only,test,256,14,NaN,0.562500,0.558569,0.600000,0.556232
13,ALL,hist_gradient_boosting,price_plus_google_reddit_small,test,256,24,NaN,0.554688,0.556109,0.568182,0.573449
14,ALL,hist_gradient_boosting,price_plus_google_small,test,256,17,NaN,0.535156,0.531360,0.573477,0.547562
15,ALL,hist_gradient_boosting,price_plus_reddit_small,test,256,21,NaN,0.562500,0.559245,0.597122,0.600873
16,ALL,logreg,price_only,test,256,14,NaN,0.554688,0.560844,0.544000,0.559860
17,ALL,logreg,price_plus_google_reddit_small,test,256,24,NaN,0.570312,0.573203,0.576923,0.585316
18,ALL,logreg,price_plus_google_small,test,256,17,NaN,0.546875,0.549591,0.553846,0.565886
19,ALL,logreg,price_plus_reddit_small,test,256,21,NaN,0.527344,0.530929,0.529183,0.570866
20,ALL,random_forest,price_only,test,256,14,NaN,0.562500,0.566009,0.565891,0.579413
21,ALL,random_forest,price_plus_google_reddit_small,test,256,24,NaN,0.566406,0.570282,0.568093,0.584087
22,ALL,random_forest,price_plus_google_small,test,256,17,NaN,0.539062,0.542397,0.542636,0.569760
23,ALL,random_forest,price_plus_reddit_small,test,256,21,NaN,0.578125,0.579721,0.590909,0.618152
24,TSLA,hist_gradient_boosting,price_only,test,128,14,44.500000,0.578125,0.581675,0.578125,0.569885
25,TSLA,hist_gradient_boosting,price_plus_google_reddit_small,test,128,24,25.958333,0.562500,0.568411,0.548387,0.600590
26,TSLA,hist_gradient_boosting,price_plus_google_small,test,128,17,36.647059,0.531250,0.533284,0.538462,0.565954
27,TSLA,hist_gradient_boosting,price_plus_reddit_small,test,128,21,29.666667,0.593750,0.592483,0.617647,0.622451
28,TSLA,logreg,price_only,test,128,14,44.500000,0.601562,0.609555,0.578512,0.618767
29,TSLA,logreg,price_plus_google_reddit_small,test,128,24,25.958333,0.617188,0.621592,0.614173,0.598870
30,TSLA,logreg,price_plus_google_small,test,128,17,36.647059,0.593750,0.598624,0.587302,0.612626
31,TSLA,logreg,price_plus_reddit_small,test,128,21,29.666667,0.554688,0.558708,0.551181,0.577745
32,TSLA,random_forest,price_only,test,128,14,44.500000,0.617188,0.625276,0.595041,0.611152
33,TSLA,random_forest,price_plus_google_reddit_small,test,128,24,25.958333,0.570312,0.576885,0.552846,0.599853
34,TSLA,random_forest,price_plus_google_small,test,128,17,36.647059,0.546875,0.552690,0.532258,0.590518
35,TSLA,random_forest,price_plus_reddit_small,test,128,21,29.666667,0.593750,0.598624,0.587302,0.628347

In [4]:
result["test_deltas"].sort_values(["ticker", "model_name", "feature_set"]).reset_index(drop=True)

,ticker,model_name,feature_set,accuracy_variant,accuracy_price,delta_accuracy,balanced_accuracy_variant,balanced_accuracy_price,delta_balanced_accuracy,roc_auc_variant,roc_auc_price,delta_roc_auc
0,AAPL,hist_gradient_boosting,price_plus_google_reddit_small,0.546875,0.546875,0.000000,0.542857,0.533990,0.008867,0.553695,0.552709,0.000985
1,AAPL,hist_gradient_boosting,price_plus_google_small,0.539062,0.546875,-0.007812,0.528325,0.533990,-0.005665,0.536946,0.552709,-0.015764
2,AAPL,hist_gradient_boosting,price_plus_reddit_small,0.531250,0.546875,-0.015625,0.525616,0.533990,-0.008374,0.583990,0.552709,0.031281
3,AAPL,logreg,price_plus_google_reddit_small,0.523438,0.507812,0.015625,0.524384,0.511576,0.012808,0.551232,0.497044,0.054187
4,AAPL,logreg,price_plus_google_small,0.500000,0.507812,-0.007812,0.500000,0.511576,-0.011576,0.510591,0.497044,0.013547
5,AAPL,logreg,price_plus_reddit_small,0.500000,0.507812,-0.007812,0.502956,0.511576,-0.008621,0.553448,0.497044,0.056404
6,AAPL,random_forest,price_plus_google_reddit_small,0.562500,0.507812,0.054688,0.563054,0.505665,0.057389,0.572906,0.538177,0.034729
7,AAPL,random_forest,price_plus_google_small,0.531250,0.507812,0.023438,0.531527,0.505665,0.025862,0.547291,0.538177,0.009113
8,AAPL,random_forest,price_plus_reddit_small,0.562500,0.507812,0.054688,0.560099,0.505665,0.054433,0.614286,0.538177,0.076108
9,ALL,hist_gradient_boosting,price_plus_google_reddit_small,0.554688,0.562500,-0.007812,0.556109,0.558569,-0.002460,0.573449,0.556232,0.017217
10,ALL,hist_gradient_boosting,price_plus_google_small,0.535156,0.562500,-0.027344,0.531360,0.558569,-0.027209,0.547562,0.556232,-0.008670
11,ALL,hist_gradient_boosting,price_plus_reddit_small,0.562500,0.562500,0.000000,0.559245,0.558569,0.000676,0.600873,0.556232,0.044641
12,ALL,logreg,price_plus_google_reddit_small,0.570312,0.554688,0.015625,0.573203,0.560844,0.012359,0.585316,0.559860,0.025457
13,ALL,logreg,price_plus_google_small,0.546875,0.554688,-0.007812,0.549591,0.560844,-0.011253,0.565886,0.559860,0.006026
14,ALL,logreg,price_plus_reddit_small,0.527344,0.554688,-0.027344,0.530929,0.560844,-0.029915,0.570866,0.559860,0.011007
15,ALL,random_forest,price_plus_google_reddit_small,0.566406,0.562500,0.003906,0.570282,0.566009,0.004274,0.584087,0.579413,0.004673
16,ALL,random_forest,price_plus_google_small,0.539062,0.562500,-0.023438,0.542397,0.566009,-0.023612,0.569760,0.579413,-0.009654
17,ALL,random_forest,price_plus_reddit_small,0.578125,0.562500,0.015625,0.579721,0.566009,0.013712,0.618152,0.579413,0.038738
18,TSLA,hist_gradient_boosting,price_plus_google_reddit_small,0.562500,0.578125,-0.015625,0.568411,0.581675,-0.013265,0.600590,0.569885,0.030705
19,TSLA,hist_gradient_boosting,price_plus_google_small,0.531250,0.578125,-0.046875,0.533284,0.581675,-0.048391,0.565954,0.569885,-0.003930
20,TSLA,hist_gradient_boosting,price_plus_reddit_small,0.593750,0.578125,0.015625,0.592483,0.581675,0.010808,0.622451,0.569885,0.052567
21,TSLA,logreg,price_plus_google_reddit_small,0.617188,0.601562,0.015625,0.621592,0.609555,0.012036,0.598870,0.618767,-0.019897
22,TSLA,logreg,price_plus_google_small,0.593750,0.601562,-0.007812,0.598624,0.609555,-0.010931,0.612626,0.618767,-0.006141
23,TSLA,logreg,price_plus_reddit_small,0.554688,0.601562,-0.046875,0.558708,0.609555,-0.050847,0.577745,0.618767,-0.041022
24,TSLA,random_forest,price_plus_google_reddit_small,0.570312,0.617188,-0.046875,0.576885,0.625276,-0.048391,0.599853,0.611152,-0.011299
25,TSLA,random_forest,price_plus_google_small,0.546875,0.617188,-0.070312,0.552690,0.625276,-0.072587,0.590518,0.611152,-0.020634
26,TSLA,random_forest,price_plus_reddit_small,0.593750,0.617188,-0.023438,0.598624,0.625276,-0.026652,0.628347,0.611152,0.017195

,ticker,model_name,feature_set,accuracy_variant,accuracy_price,delta_accuracy,balanced_accuracy_variant,balanced_accuracy_price,delta_balanced_accuracy,roc_auc_variant,roc_auc_price,delta_roc_auc
0,AAPL,hist_gradient_boosting,price_plus_google_reddit_small,0.546875,0.546875,0.000000,0.542857,0.533990,0.008867,0.553695,0.552709,0.000985
1,AAPL,hist_gradient_boosting,price_plus_google_small,0.539062,0.546875,-0.007812,0.528325,0.533990,-0.005665,0.536946,0.552709,-0.015764
2,AAPL,hist_gradient_boosting,price_plus_reddit_small,0.531250,0.546875,-0.015625,0.525616,0.533990,-0.008374,0.583990,0.552709,0.031281
3,AAPL,logreg,price_plus_google_reddit_small,0.523438,0.507812,0.015625,0.524384,0.511576,0.012808,0.551232,0.497044,0.054187
4,AAPL,logreg,price_plus_google_small,0.500000,0.507812,-0.007812,0.500000,0.511576,-0.011576,0.510591,0.497044,0.013547
5,AAPL,logreg,price_plus_reddit_small,0.500000,0.507812,-0.007812,0.502956,0.511576,-0.008621,0.553448,0.497044,0.056404
6,AAPL,random_forest,price_plus_google_reddit_small,0.562500,0.507812,0.054688,0.563054,0.505665,0.057389,0.572906,0.538177,0.034729
7,AAPL,random_forest,price_plus_google_small,0.531250,0.507812,0.023438,0.531527,0.505665,0.025862,0.547291,0.538177,0.009113
8,AAPL,random_forest,price_plus_reddit_small,0.562500,0.507812,0.054688,0.560099,0.505665,0.054433,0.614286,0.538177,0.076108
9,ALL,hist_gradient_boosting,price_plus_google_reddit_small,0.554688,0.562500,-0.007812,0.556109,0.558569,-0.002460,0.573449,0.556232,0.017217
10,ALL,hist_gradient_boosting,price_plus_google_small,0.535156,0.562500,-0.027344,0.531360,0.558569,-0.027209,0.547562,0.556232,-0.008670
11,ALL,hist_gradient_boosting,price_plus_reddit_small,0.562500,0.562500,0.000000,0.559245,0.558569,0.000676,0.600873,0.556232,0.044641
12,ALL,logreg,price_plus_google_reddit_small,0.570312,0.554688,0.015625,0.573203,0.560844,0.012359,0.585316,0.559860,0.025457
13,ALL,logreg,price_plus_google_small,0.546875,0.554688,-0.007812,0.549591,0.560844,-0.011253,0.565886,0.559860,0.006026
14,ALL,logreg,price_plus_reddit_small,0.527344,0.554688,-0.027344,0.530929,0.560844,-0.029915,0.570866,0.559860,0.011007
15,ALL,random_forest,price_plus_google_reddit_small,0.566406,0.562500,0.003906,0.570282,0.566009,0.004274,0.584087,0.579413,0.004673
16,ALL,random_forest,price_plus_google_small,0.539062,0.562500,-0.023438,0.542397,0.566009,-0.023612,0.569760,0.579413,-0.009654
17,ALL,random_forest,price_plus_reddit_small,0.578125,0.562500,0.015625,0.579721,0.566009,0.013712,0.618152,0.579413,0.038738
18,TSLA,hist_gradient_boosting,price_plus_google_reddit_small,0.562500,0.578125,-0.015625,0.568411,0.581675,-0.013265,0.600590,0.569885,0.030705
19,TSLA,hist_gradient_boosting,price_plus_google_small,0.531250,0.578125,-0.046875,0.533284,0.581675,-0.048391,0.565954,0.569885,-0.003930
20,TSLA,hist_gradient_boosting,price_plus_reddit_small,0.593750,0.578125,0.015625,0.592483,0.581675,0.010808,0.622451,0.569885,0.052567
21,TSLA,logreg,price_plus_google_reddit_small,0.617188,0.601562,0.015625,0.621592,0.609555,0.012036,0.598870,0.618767,-0.019897
22,TSLA,logreg,price_plus_google_small,0.593750,0.601562,-0.007812,0.598624,0.609555,-0.010931,0.612626,0.618767,-0.006141
23,TSLA,logreg,price_plus_reddit_small,0.554688,0.601562,-0.046875,0.558708,0.609555,-0.050847,0.577745,0.618767,-0.041022
24,TSLA,random_forest,price_plus_google_reddit_small,0.570312,0.617188,-0.046875,0.576885,0.625276,-0.048391,0.599853,0.611152,-0.011299
25,TSLA,random_forest,price_plus_google_small,0.546875,0.617188,-0.070312,0.552690,0.625276,-0.072587,0.590518,0.611152,-0.020634
26,TSLA,random_forest,price_plus_reddit_small,0.593750,0.617188,-0.023438,0.598624,0.625276,-0.026652,0.628347,0.611152,0.017195

In [6]:
result["metrics"].query("split == 'test'").pivot_table(
    index=["ticker", "model_name"],
    columns="feature_set",
    values="balanced_accuracy",
)

feature_set                    price_only  price_plus_google_reddit_small  \
ticker model_name
AAPL   hist_gradient_boosting    0.533990                        0.542857
       logreg                    0.511576                        0.524384
       random_forest             0.505665                        0.563054
ALL    hist_gradient_boosting    0.558569                        0.556109
       logreg                    0.560844                        0.573203
       random_forest             0.566009                        0.570282
TSLA   hist_gradient_boosting    0.581675                        0.568411
       logreg                    0.609555                        0.621592
       random_forest             0.625276                        0.576885

feature_set                    price_plus_google_small  \
ticker model_name
AAPL   hist_gradient_boosting                 0.528325
       logreg                                 0.500000
       random_forest                          0.531527
ALL    hist_gradient_boosting                 0.531360
       logreg                                 0.549591
       random_forest                          0.542397
TSLA   hist_gradient_boosting                 0.533284
       logreg                                 0.598624
       random_forest                          0.552690

feature_set                    price_plus_reddit_small
ticker model_name
AAPL   hist_gradient_boosting                 0.525616
       logreg                                 0.502956
       random_forest                          0.560099
ALL    hist_gradient_boosting                 0.559245
       logreg                                 0.530929
       random_forest                          0.579721
TSLA   hist_gradient_boosting                 0.592483
       logreg                                 0.558708
       random_forest                          0.598624

feature_set                    price_only  price_plus_google_reddit_small  \
ticker model_name
AAPL   hist_gradient_boosting    0.533990                        0.542857
       logreg                    0.511576                        0.524384
       random_forest             0.505665                        0.563054
ALL    hist_gradient_boosting    0.558569                        0.556109
       logreg                    0.560844                        0.573203
       random_forest             0.566009                        0.570282
TSLA   hist_gradient_boosting    0.581675                        0.568411
       logreg                    0.609555                        0.621592
       random_forest             0.625276                        0.576885

feature_set                    price_plus_google_small  \
ticker model_name
AAPL   hist_gradient_boosting                 0.528325
       logreg                                 0.500000
       random_forest                          0.531527
ALL    hist_gradient_boosting                 0.531360
       logreg                                 0.549591
       random_forest                          0.542397
TSLA   hist_gradient_boosting                 0.533284
       logreg                                 0.598624
       random_forest                          0.552690

feature_set                    price_plus_reddit_small
ticker model_name
AAPL   hist_gradient_boosting                 0.525616
       logreg                                 0.502956
       random_forest                          0.560099
ALL    hist_gradient_boosting                 0.559245
       logreg                                 0.530929
       random_forest                          0.579721
TSLA   hist_gradient_boosting                 0.592483
       logreg                                 0.558708
       random_forest                          0.598624

In [8]:
result["metrics"].query("split == 'test'").pivot_table(
    index=["ticker", "model_name"],
    columns="feature_set",
    values="roc_auc",
)

feature_set                    price_only  price_plus_google_reddit_small  \
ticker model_name
AAPL   hist_gradient_boosting    0.552709                        0.553695
       logreg                    0.497044                        0.551232
       random_forest             0.538177                        0.572906
ALL    hist_gradient_boosting    0.556232                        0.573449
       logreg                    0.559860                        0.585316
       random_forest             0.579413                        0.584087
TSLA   hist_gradient_boosting    0.569885                        0.600590
       logreg                    0.618767                        0.598870
       random_forest             0.611152                        0.599853

feature_set                    price_plus_google_small  \
ticker model_name
AAPL   hist_gradient_boosting                 0.536946
       logreg                                 0.510591
       random_forest                          0.547291
ALL    hist_gradient_boosting                 0.547562
       logreg                                 0.565886
       random_forest                          0.569760
TSLA   hist_gradient_boosting                 0.565954
       logreg                                 0.612626
       random_forest                          0.590518

feature_set                    price_plus_reddit_small
ticker model_name
AAPL   hist_gradient_boosting                 0.583990
       logreg                                 0.553448
       random_forest                          0.614286
ALL    hist_gradient_boosting                 0.600873
       logreg                                 0.570866
       random_forest                          0.618152
TSLA   hist_gradient_boosting                 0.622451
       logreg                                 0.577745
       random_forest                          0.628347

feature_set                    price_only  price_plus_google_reddit_small  \
ticker model_name
AAPL   hist_gradient_boosting    0.552709                        0.553695
       logreg                    0.497044                        0.551232
       random_forest             0.538177                        0.572906
ALL    hist_gradient_boosting    0.556232                        0.573449
       logreg                    0.559860                        0.585316
       random_forest             0.579413                        0.584087
TSLA   hist_gradient_boosting    0.569885                        0.600590
       logreg                    0.618767                        0.598870
       random_forest             0.611152                        0.599853

feature_set                    price_plus_google_small  \
ticker model_name
AAPL   hist_gradient_boosting                 0.536946
       logreg                                 0.510591
       random_forest                          0.547291
ALL    hist_gradient_boosting                 0.547562
       logreg                                 0.565886
       random_forest                          0.569760
TSLA   hist_gradient_boosting                 0.565954
       logreg                                 0.612626
       random_forest                          0.590518

feature_set                    price_plus_reddit_small
ticker model_name
AAPL   hist_gradient_boosting                 0.583990
       logreg                                 0.553448
       random_forest                          0.614286
ALL    hist_gradient_boosting                 0.600873
       logreg                                 0.570866
       random_forest                          0.618152
TSLA   hist_gradient_boosting                 0.622451
       logreg                                 0.577745
       random_forest                          0.628347

In [10]:
result["metrics"].query("split == 'train'").pivot_table(
    index=["ticker", "model_name"],
    columns="feature_set",
    values="balanced_accuracy",
)

feature_set                    price_only  price_plus_google_reddit_small  \
ticker model_name
AAPL   hist_gradient_boosting    0.874563                        0.943695
       logreg                    0.535277                        0.542529
       random_forest             0.877369                        0.889541
ALL    hist_gradient_boosting    0.891913                        0.948316
       logreg                    0.544684                        0.573850
       random_forest             0.837600                        0.881679
TSLA   hist_gradient_boosting    0.906619                        0.951801
       logreg                    0.552299                        0.603701
       random_forest             0.795527                        0.873027

feature_set                    price_plus_google_small  \
ticker model_name
AAPL   hist_gradient_boosting                 0.905722
       logreg                                 0.540780
       random_forest                          0.884694
ALL    hist_gradient_boosting                 0.913295
       logreg                                 0.549000
       random_forest                          0.854687
TSLA   hist_gradient_boosting                 0.919276
       logreg                                 0.556188
       random_forest                          0.823859

feature_set                    price_plus_reddit_small
ticker model_name
AAPL   hist_gradient_boosting                 0.908345
       logreg                                 0.542055
       random_forest                          0.884038
ALL    hist_gradient_boosting                 0.918651
       logreg                                 0.556424
       random_forest                          0.861358
TSLA   hist_gradient_boosting                 0.927751
       logreg                                 0.569041
       random_forest                          0.837975

feature_set                    price_only  price_plus_google_reddit_small  \
ticker model_name
AAPL   hist_gradient_boosting    0.874563                        0.943695
       logreg                    0.535277                        0.542529
       random_forest             0.877369                        0.889541
ALL    hist_gradient_boosting    0.891913                        0.948316
       logreg                    0.544684                        0.573850
       random_forest             0.837600                        0.881679
TSLA   hist_gradient_boosting    0.906619                        0.951801
       logreg                    0.552299                        0.603701
       random_forest             0.795527                        0.873027

feature_set                    price_plus_google_small  \
ticker model_name
AAPL   hist_gradient_boosting                 0.905722
       logreg                                 0.540780
       random_forest                          0.884694
ALL    hist_gradient_boosting                 0.913295
       logreg                                 0.549000
       random_forest                          0.854687
TSLA   hist_gradient_boosting                 0.919276
       logreg                                 0.556188
       random_forest                          0.823859

feature_set                    price_plus_reddit_small
ticker model_name
AAPL   hist_gradient_boosting                 0.908345
       logreg                                 0.542055
       random_forest                          0.884038
ALL    hist_gradient_boosting                 0.918651
       logreg                                 0.556424
       random_forest                          0.861358
TSLA   hist_gradient_boosting                 0.927751
       logreg                                 0.569041
       random_forest                          0.837975