# Strict Single-Source Alt-Data Ablation

This notebook reruns single-ticker experiments with stricter methodology.

Tickers:
- `TSLA`
- `AAPL`

Feature sets:
- `price_only`
- `price_plus_google_trends`
- `price_plus_gdelt`
- `price_plus_reddit_sentiment`
- `price_plus_reddit_attention`

For each alt-data source, the feature block uses:
- `t-1`
- `t-2`
- `rolling 3d`
- `rolling 5d`
- `surprise vs rolling baseline`

Models:
- `logreg`
- `svm_rbf`
- `random_forest`
- `hist_gradient_boosting`
- `mlp_small`

Methodology additions:
- strict time alignment: all alt-data shifted by one trading day before transforms
- threshold tuning for `svm_rbf` and `mlp_small` using train/validation only
- block-bootstrap confidence intervals for balanced accuracy and ROC AUC
- DeLong test for AUC vs `price_only`
- walk-forward fold metrics and fold-by-fold deltas vs `price_only`

Artifacts are written to `notebooks_two_tickers/outputs/strict_source_ablation`.

In [1]:
import pandas as pd

from strict_source_ablation_experiment import run_strict_source_ablation_experiment

pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 320)

In [2]:
result = run_strict_source_ablation_experiment()

print(f"Dataset: {result['dataset_path']}")
print(f"Metrics: {result['metrics_path']}")
print(f"Predictions: {result['predictions_path']}")
print(f"Threshold tuning: {result['tuning_path']}")
print(f"Bootstrap summary: {result['bootstrap_path']}")
print(f"Fold metrics: {result['cv_fold_path']}")
print(f"Fold deltas: {result['cv_delta_path']}")
print(f"DeLong summary: {result['delong_path']}")
print(f"Metadata: {result['metadata_path']}")

Dataset: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\datasets\stock_direction_two_tickers_base.csv
Metrics: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\strict_source_ablation\metrics.csv
Predictions: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\strict_source_ablation\predictions.csv
Threshold tuning: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\strict_source_ablation\threshold_tuning.csv
Bootstrap summary: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\strict_source_ablation\bootstrap_summary.csv
Fold metrics: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\strict_source_ablation\cv_fold_metrics.csv
Fold deltas: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\strict_source_ablation\cv_fold_deltas_vs_price_only.csv
DeLong summary: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\strict_source_ablation\delong_vs_price_only.csv
Metadata: C:\Users\user\OneDrive\Documents\magisterka\praca magisterska\code\notebooks_two_tickers\outputs\strict_source_ablation\run_metadata.json

In [3]:
test_metrics = result["metrics"].query("split == 'test'").copy()
test_metrics = test_metrics.sort_values(["ticker", "model_name", "feature_set"]).reset_index(drop=True)
test_metrics

   ticker              model_name                  feature_set split  n_rows  n_features  train_rows_per_feature  decision_threshold  threshold_tuned  validation_rows  validation_balanced_accuracy  accuracy  balanced_accuracy        f1   roc_auc
0    AAPL  hist_gradient_boosting                   price_only  test     128          14               44.500000                0.50            False                0                           NaN  0.546875           0.533990  0.618421  0.552709
1    AAPL  hist_gradient_boosting             price_plus_gdelt  test     128          29               21.482759                0.50            False                0                           NaN  0.492188           0.492857  0.511278  0.541872
2    AAPL  hist_gradient_boosting     price_plus_google_trends  test     128          19               32.789474                0.50            False                0                           NaN  0.531250           0.515271  0.615385  0.540148
3    AAPL  hist_gradient_boosting  price_plus_reddit_attention  test     128          34               18.323529                0.50            False                0                           NaN  0.523438           0.511084  0.596026  0.525616
4    AAPL  hist_gradient_boosting  price_plus_reddit_sentiment  test     128          34               18.323529                0.50            False                0                           NaN  0.593750           0.590148  0.628571  0.595567
5    AAPL                  logreg                   price_only  test     128          14               44.500000                0.50            False                0                           NaN  0.507812           0.511576  0.511628  0.497044
6    AAPL                  logreg             price_plus_gdelt  test     128          29               21.482759                0.50            False                0                           NaN  0.468750           0.455172  0.552632  0.490394
7    AAPL                  logreg     price_plus_google_trends  test     128          19               32.789474                0.50            False                0                           NaN  0.531250           0.533005  0.545455  0.535961
8    AAPL                  logreg  price_plus_reddit_attention  test     128          34               18.323529                0.50            False                0                           NaN  0.515625           0.506897  0.575342  0.503695
9    AAPL                  logreg  price_plus_reddit_sentiment  test     128          34               18.323529                0.50            False                0                           NaN  0.500000           0.498522  0.529412  0.505911
10   AAPL               mlp_small                   price_only  test     128          14               44.500000                0.55             True              125                      0.597336  0.523438           0.521429  0.554745  0.544828
11   AAPL               mlp_small             price_plus_gdelt  test     128          29               21.482759                0.60             True              125                      0.552126  0.500000           0.528079  0.333333  0.464286
12   AAPL               mlp_small     price_plus_google_trends  test     128          19               32.789474                0.61             True              125                      0.625128  0.500000           0.517734  0.418182  0.523892
13   AAPL               mlp_small  price_plus_reddit_attention  test     128          34               18.323529                0.68             True              125                      0.506916  0.460938           0.504187  0.080000  0.469212
14   AAPL               mlp_small  price_plus_reddit_sentiment  test     128          34               18.323529                0.57             True              125                      0.596568  0.453125           0.454187  0.469697  0.469212
15   AAPL           random_forest                   price_only  test     128          14               44.500000                0.50            False                0                           NaN  0.507812           0.505665  0.540146  0.538177
16   AAPL           random_forest             price_plus_gdelt  test     128          29               21.482759                0.50            False                0                           NaN  0.570312           0.567241  0.604317  0.559113
17   AAPL           random_forest     price_plus_google_trends  test     128          19               32.789474                0.50            False                0                           NaN  0.476562           0.474138  0.510949  0.522167
18   AAPL           random_forest  price_plus_reddit_attention  test     128          34               18.323529                0.50            False                0                           NaN  0.539062           0.532759  0.587413  0.507143
19   AAPL           random_forest  price_plus_reddit_sentiment  test     128          34               18.323529                0.50            False                0                           NaN  0.578125           0.581773  0.584615  0.561576
20   AAPL                 svm_rbf                   price_only  test     128          14               44.500000                0.52             True              125                      0.512167  0.500000           0.471921  0.627907  0.475000
21   AAPL                 svm_rbf             price_plus_gdelt  test     128          29               21.482759                0.53             True              125                      0.518058  0.476562           0.449015  0.608187  0.452833
22   AAPL                 svm_rbf     price_plus_google_trends  test     128          19               32.789474                0.54             True              125                      0.553535  0.492188           0.492857  0.511278  0.485961
23   AAPL                 svm_rbf  price_plus_reddit_attention  test     128          34               18.323529                0.55             True              125                      0.551230  0.421875           0.431527  0.383333  0.428079
24   AAPL                 svm_rbf  price_plus_reddit_sentiment  test     128          34               18.323529                0.54             True              125                      0.507812  0.523438           0.499261  0.634731  0.491256
25   TSLA  hist_gradient_boosting                   price_only  test     128          14               44.500000                0.50            False                0                           NaN  0.578125           0.581675  0.578125  0.569885
26   TSLA  hist_gradient_boosting             price_plus_gdelt  test     128          29               21.482759                0.50            False                0                           NaN  0.578125           0.576762  0.602941  0.572095
27   TSLA  hist_gradient_boosting     price_plus_google_trends  test     128          19               32.789474                0.50            False                0                           NaN  0.453125           0.463277  0.396552  0.507492
28   TSLA  hist_gradient_boosting  price_plus_reddit_attention  test     128          34               18.323529                0.50            False                0                           NaN  0.539062           0.545443  0.520325  0.613854
29   TSLA  hist_gradient_boosting  price_plus_reddit_sentiment  test     128          34               18.323529                0.50            False                0                           NaN  0.500000           0.503070  0.500000  0.488578
30   TSLA                  logreg                   price_only  test     128          14               44.500000                0.50            False                0                           NaN  0.601562           0.609555  0.578512  0.618767
31   TSLA                  logreg             price_plus_gdelt  test     128          29               21.482759                0.50            False                0                           NaN  0.546875           0.542864  0.585714  0.540162
32   TSLA                  logreg     price_plus_google_trends  test     128          19               32.789474                0.50            False                0                           NaN  0.617188           0.624048  0.601626  0.628592
33   TSLA                  logreg  price_plus_reddit_attention  test     128          34               18.323529                0.50            False                0                           NaN  0.593750           0.596168  0.600000  0.591255
34   TSLA                  logreg  price_plus_reddit_sentiment  test     128          34               18.323529                0.50            False                0                           NaN  0.570312           0.574429  0.566929  0.581921
35   TSLA               mlp_small                   price_only  test     128          14               44.500000                0.49             True              125                      0.550310  0.640625           0.634733  0.680556  0.650209
36   TSLA               mlp_small             price_plus_gdelt  test     128          29               21.482759                0.68             True              125                      0.594298  0.453125           0.491525  0.000000  0.344141
37   TSLA               mlp_small     price_plus_google_trends  test     128          19               32.789474                0.70             True              125                      0.543344  0.445312           0.481823  0.027397  0.416851
38   TSLA               mlp_small  price_plus_reddit_attention  test     128          34               18.323529                0.70             True              125                      0.565402  0.468750           0.507246  0.028571  0.664210
39   TSLA               mlp_small  price_plus_reddit_sentiment  test     128          34               18.323529                0.70             True              125                      0.534830  0.476562           0.514493  0.056338  0.534758
40   TSLA           random_forest                   price_only  test     128          14               44.500000                0.50            False                0                           NaN  0.617188           0.625276  0.595041  0.611152
41   TSLA           random_forest             price_plus_gdelt  test     128          29               21.482759                0.50            False                0                           NaN  0.578125           0.573078  0.619718  0.571850
42   TSLA           random_forest     price_plus_google_trends  test     128          19               32.789474                0.50            False                0                           NaN  0.578125           0.590273  0.526316  0.606485
43   TSLA           random_forest  price_plus_reddit_attention  test     128          34               18.323529                0.50            False                0                           NaN  0.562500           0.565954  0.562500  0.591501
44   TSLA           random_forest  price_plus_reddit_sentiment  test     128          34               18.323529                0.50            False                0                           NaN  0.593750           0.596168  0.600000  0.573815
45   TSLA                 svm_rbf                   price_only  test     128          14               44.500000                0.51             True              125                      0.525413  0.609375           0.604520  0.647887  0.607222
46   TSLA                 svm_rbf             price_plus_gdelt  test     128          29               21.482759                0.54             True              125                      0.574303  0.445312           0.454802  0.393162  0.515352
47   TSLA                 svm_rbf     price_plus_google_trends  test     128          19               32.789474                0.53             True              125                      0.540506  0.492188           0.511791  0.356436  0.581552
48   TSLA                 svm_rbf  price_plus_reddit_attention  test     128          34               18.323529                0.55             True              125                      0.520382  0.460938           0.500000  0.000000  0.469049
49   TSLA                 svm_rbf  price_plus_reddit_sentiment  test     128          34               18.323529                0.47             True              125                      0.539861  0.539062           0.500000  0.700508  0.438958

In [4]:
summary = test_metrics.pivot_table(
    index=["ticker", "model_name"],
    columns="feature_set",
    values=["balanced_accuracy", "roc_auc"],
)
summary

                              balanced_accuracy                                                                                                      roc_auc
feature_set                          price_only price_plus_gdelt price_plus_google_trends price_plus_reddit_attention price_plus_reddit_sentiment price_only price_plus_gdelt price_plus_google_trends price_plus_reddit_attention price_plus_reddit_sentiment
ticker model_name
AAPL   hist_gradient_boosting          0.533990         0.492857                 0.515271                    0.511084                    0.590148   0.552709         0.541872                 0.540148                    0.525616                    0.595567
       logreg                          0.511576         0.455172                 0.533005                    0.506897                    0.498522   0.497044         0.490394                 0.535961                    0.503695                    0.505911
       mlp_small                       0.521429         0.528079                 0.517734                    0.504187                    0.454187   0.544828         0.464286                 0.523892                    0.469212                    0.469212
       random_forest                   0.505665         0.567241                 0.474138                    0.532759                    0.581773   0.538177         0.559113                 0.522167                    0.507143                    0.561576
       svm_rbf                         0.471921         0.449015                 0.492857                    0.431527                    0.499261   0.475000         0.452833                 0.485961                    0.428079                    0.491256
TSLA   hist_gradient_boosting          0.581675         0.576762                 0.463277                    0.545443                    0.503070   0.569885         0.572095                 0.507492                    0.613854                    0.488578
       logreg                          0.609555         0.542864                 0.624048                    0.596168                    0.574429   0.618767         0.540162                 0.628592                    0.591255                    0.581921
       mlp_small                       0.634733         0.491525                 0.481823                    0.507246                    0.514493   0.650209         0.344141                 0.416851                    0.664210                    0.534758
       random_forest                   0.625276         0.573078                 0.590273                    0.565954                    0.596168   0.611152         0.571850                 0.606485                    0.591501                    0.573815
       svm_rbf                         0.604520         0.454802                 0.511791                    0.500000                    0.500000   0.607222         0.515352                 0.581552                    0.469049                    0.438958

In [5]:
bootstrap_summary = result["bootstrap_summary"].copy()
bootstrap_summary = bootstrap_summary.sort_values(["ticker", "model_name", "feature_set"]).reset_index(drop=True)
bootstrap_summary

   ticker              model_name                  feature_set split  decision_threshold  balanced_accuracy_ci_low  balanced_accuracy_ci_high  roc_auc_ci_low  roc_auc_ci_high
0    AAPL  hist_gradient_boosting                   price_only  test                0.50                  0.447101                   0.625798        0.443673         0.650605
1    AAPL  hist_gradient_boosting             price_plus_gdelt  test                0.50                  0.415256                   0.571469        0.459445         0.639979
2    AAPL  hist_gradient_boosting     price_plus_google_trends  test                0.50                  0.421865                   0.613139        0.429170         0.642771
3    AAPL  hist_gradient_boosting  price_plus_reddit_attention  test                0.50                  0.437690                   0.581879        0.428142         0.643613
4    AAPL  hist_gradient_boosting  price_plus_reddit_sentiment  test                0.50                  0.505594                   0.655928        0.491152         0.674205
5    AAPL                  logreg                   price_only  test                0.50                  0.429535                   0.592218        0.396055         0.604870
6    AAPL                  logreg             price_plus_gdelt  test                0.50                  0.369895                   0.541896        0.378877         0.602103
7    AAPL                  logreg     price_plus_google_trends  test                0.50                  0.468990                   0.614649        0.425585         0.652830
8    AAPL                  logreg  price_plus_reddit_attention  test                0.50                  0.418829                   0.593590        0.396339         0.609638
9    AAPL                  logreg  price_plus_reddit_sentiment  test                0.50                  0.422278                   0.580122        0.408588         0.604007
10   AAPL               mlp_small                   price_only  test                0.55                  0.430798                   0.627159        0.430032         0.679710
11   AAPL               mlp_small             price_plus_gdelt  test                0.60                  0.446278                   0.626328        0.334966         0.592117
12   AAPL               mlp_small     price_plus_google_trends  test                0.61                  0.460087                   0.613490        0.424698         0.636995
13   AAPL               mlp_small  price_plus_reddit_attention  test                0.68                  0.467948                   0.537483        0.357841         0.590599
14   AAPL               mlp_small  price_plus_reddit_sentiment  test                0.57                  0.382678                   0.555072        0.392297         0.562179
15   AAPL           random_forest                   price_only  test                0.50                  0.405031                   0.585398        0.429116         0.635975
16   AAPL           random_forest             price_plus_gdelt  test                0.50                  0.499627                   0.647068        0.456371         0.654122
17   AAPL           random_forest     price_plus_google_trends  test                0.50                  0.374339                   0.560683        0.399932         0.634906
18   AAPL           random_forest  price_plus_reddit_attention  test                0.50                  0.466696                   0.632698        0.413234         0.604932
19   AAPL           random_forest  price_plus_reddit_sentiment  test                0.50                  0.518499                   0.634632        0.459075         0.634368
20   AAPL                 svm_rbf                   price_only  test                0.52                  0.396647                   0.545243        0.373614         0.582361
21   AAPL                 svm_rbf             price_plus_gdelt  test                0.53                  0.389271                   0.518742        0.360095         0.557071
22   AAPL                 svm_rbf     price_plus_google_trends  test                0.54                  0.415199                   0.563098        0.381708         0.567546
23   AAPL                 svm_rbf  price_plus_reddit_attention  test                0.55                  0.346809                   0.508037        0.335060         0.527813
24   AAPL                 svm_rbf  price_plus_reddit_sentiment  test                0.54                  0.425683                   0.571110        0.405144         0.603655
25   TSLA  hist_gradient_boosting                   price_only  test                0.50                  0.495843                   0.669517        0.484670         0.678634
26   TSLA  hist_gradient_boosting             price_plus_gdelt  test                0.50                  0.490481                   0.651742        0.468897         0.669617
27   TSLA  hist_gradient_boosting     price_plus_google_trends  test                0.50                  0.385632                   0.564217        0.429652         0.606351
28   TSLA  hist_gradient_boosting  price_plus_reddit_attention  test                0.50                  0.463476                   0.626380        0.517414         0.723398
29   TSLA  hist_gradient_boosting  price_plus_reddit_sentiment  test                0.50                  0.404720                   0.585321        0.379271         0.584437
30   TSLA                  logreg                   price_only  test                0.50                  0.546619                   0.676451        0.546419         0.698664
31   TSLA                  logreg             price_plus_gdelt  test                0.50                  0.452491                   0.625304        0.437875         0.647514
32   TSLA                  logreg     price_plus_google_trends  test                0.50                  0.543649                   0.690661        0.557028         0.712764
33   TSLA                  logreg  price_plus_reddit_attention  test                0.50                  0.508323                   0.677609        0.498958         0.688651
34   TSLA                  logreg  price_plus_reddit_sentiment  test                0.50                  0.508236                   0.649820        0.494809         0.652211
35   TSLA               mlp_small                   price_only  test                0.49                  0.522716                   0.717112        0.546272         0.730714
36   TSLA               mlp_small             price_plus_gdelt  test                0.68                  0.473189                   0.500000        0.246445         0.453768
37   TSLA               mlp_small     price_plus_google_trends  test                0.70                  0.459664                   0.500000        0.294253         0.533757
38   TSLA               mlp_small  price_plus_reddit_attention  test                0.70                  0.500000                   0.523447        0.556037         0.767503
39   TSLA               mlp_small  price_plus_reddit_sentiment  test                0.70                  0.500000                   0.539073        0.459129         0.622313
40   TSLA           random_forest                   price_only  test                0.50                  0.536864                   0.692127        0.505132         0.692950
41   TSLA           random_forest             price_plus_gdelt  test                0.50                  0.472890                   0.656442        0.453943         0.660694
42   TSLA           random_forest     price_plus_google_trends  test                0.50                  0.505968                   0.663733        0.496034         0.684414
43   TSLA           random_forest  price_plus_reddit_attention  test                0.50                  0.470396                   0.651872        0.478170         0.688354
44   TSLA           random_forest  price_plus_reddit_sentiment  test                0.50                  0.482795                   0.678674        0.466733         0.660620
45   TSLA                 svm_rbf                   price_only  test                0.51                  0.523750                   0.680826        0.510226         0.697059
46   TSLA                 svm_rbf             price_plus_gdelt  test                0.54                  0.371576                   0.523158        0.405867         0.614951
47   TSLA                 svm_rbf     price_plus_google_trends  test                0.53                  0.423775                   0.580434        0.461203         0.684107
48   TSLA                 svm_rbf  price_plus_reddit_attention  test                0.55                  0.500000                   0.500000        0.365142         0.563438
49   TSLA                 svm_rbf  price_plus_reddit_sentiment  test                0.47                  0.500000                   0.500000        0.355130         0.532491

In [6]:
delong_summary = result["delong_summary"].copy()
delong_summary = delong_summary.sort_values(["ticker", "model_name", "feature_set_alt"]).reset_index(drop=True)
delong_summary

   ticker              model_name              feature_set_alt     auc_a     auc_b  auc_diff  auc_diff_se    z_stat   p_value
0    AAPL  hist_gradient_boosting             price_plus_gdelt  0.552709  0.541872  0.010837     0.049747  0.217851  0.827545
1    AAPL  hist_gradient_boosting     price_plus_google_trends  0.552709  0.540148  0.012562     0.028816  0.435918  0.662896
2    AAPL  hist_gradient_boosting  price_plus_reddit_attention  0.552709  0.525616  0.027094     0.050406  0.537511  0.590915
3    AAPL  hist_gradient_boosting  price_plus_reddit_sentiment  0.552709  0.595567 -0.042857     0.053298 -0.804100  0.421339
4    AAPL                  logreg             price_plus_gdelt  0.497044  0.490394  0.006650     0.037297  0.178306  0.858482
5    AAPL                  logreg     price_plus_google_trends  0.497044  0.535961 -0.038916     0.032861 -1.184267  0.236307
6    AAPL                  logreg  price_plus_reddit_attention  0.497044  0.503695 -0.006650     0.037845 -0.175725  0.860510
7    AAPL                  logreg  price_plus_reddit_sentiment  0.497044  0.505911 -0.008867     0.043389 -0.204360  0.838072
8    AAPL               mlp_small             price_plus_gdelt  0.544828  0.464286  0.080542     0.075238  1.070499  0.284395
9    AAPL               mlp_small     price_plus_google_trends  0.544828  0.523892  0.020936     0.054891  0.381411  0.702898
10   AAPL               mlp_small  price_plus_reddit_attention  0.544828  0.469212  0.075616     0.072680  1.040391  0.298158
11   AAPL               mlp_small  price_plus_reddit_sentiment  0.544828  0.469212  0.075616     0.079007  0.957079  0.338527
12   AAPL           random_forest             price_plus_gdelt  0.538177  0.559113 -0.020936     0.062790 -0.333428  0.738811
13   AAPL           random_forest     price_plus_google_trends  0.538177  0.522167  0.016010     0.034293  0.466852  0.640606
14   AAPL           random_forest  price_plus_reddit_attention  0.538177  0.507143  0.031034     0.064512  0.481064  0.630471
15   AAPL           random_forest  price_plus_reddit_sentiment  0.538177  0.561576 -0.023399     0.058790 -0.398010  0.690623
16   AAPL                 svm_rbf             price_plus_gdelt  0.475000  0.452833  0.022167     0.069486  0.319023  0.749709
17   AAPL                 svm_rbf     price_plus_google_trends  0.475000  0.485961 -0.010961     0.048004 -0.228325  0.819394
18   AAPL                 svm_rbf  price_plus_reddit_attention  0.475000  0.428079  0.046921     0.069364  0.676453  0.498753
19   AAPL                 svm_rbf  price_plus_reddit_sentiment  0.475000  0.491256 -0.016256     0.062743 -0.259093  0.795564
20   TSLA  hist_gradient_boosting             price_plus_gdelt  0.569885  0.572095 -0.002211     0.053647 -0.041209  0.967129
21   TSLA  hist_gradient_boosting     price_plus_google_trends  0.569885  0.507492  0.062393     0.040750  1.531113  0.125741
22   TSLA  hist_gradient_boosting  price_plus_reddit_attention  0.569885  0.613854 -0.043970     0.050575 -0.869401  0.384628
23   TSLA  hist_gradient_boosting  price_plus_reddit_sentiment  0.569885  0.488578  0.081307     0.055526  1.464314  0.143108
24   TSLA                  logreg             price_plus_gdelt  0.618767  0.540162  0.078605     0.042698  1.840960  0.065627
25   TSLA                  logreg     price_plus_google_trends  0.618767  0.628592 -0.009826     0.020105 -0.488726  0.625036
26   TSLA                  logreg  price_plus_reddit_attention  0.618767  0.591255  0.027512     0.038968  0.705998  0.480189
27   TSLA                  logreg  price_plus_reddit_sentiment  0.618767  0.581921  0.036846     0.033516  1.099347  0.271617
28   TSLA               mlp_small             price_plus_gdelt  0.650209  0.344141  0.306067     0.078307  3.908541  0.000093
29   TSLA               mlp_small     price_plus_google_trends  0.650209  0.416851  0.233358     0.068705  3.396495  0.000683
30   TSLA               mlp_small  price_plus_reddit_attention  0.650209  0.664210 -0.014001     0.056894 -0.246096  0.805608
31   TSLA               mlp_small  price_plus_reddit_sentiment  0.650209  0.534758  0.115451     0.064237  1.797269  0.072293
32   TSLA           random_forest             price_plus_gdelt  0.611152  0.571850  0.039302     0.045055  0.872316  0.383036
33   TSLA           random_forest     price_plus_google_trends  0.611152  0.606485  0.004667     0.022373  0.208607  0.834755
34   TSLA           random_forest  price_plus_reddit_attention  0.611152  0.591501  0.019651     0.038544  0.509832  0.610169
35   TSLA           random_forest  price_plus_reddit_sentiment  0.611152  0.573815  0.037337     0.042047  0.887987  0.374548
36   TSLA                 svm_rbf             price_plus_gdelt  0.607222  0.515352  0.091869     0.053801  1.707575  0.087715
37   TSLA                 svm_rbf     price_plus_google_trends  0.607222  0.581552  0.025669     0.045282  0.566883  0.570793
38   TSLA                 svm_rbf  price_plus_reddit_attention  0.607222  0.469049  0.138172     0.087583  1.577624  0.114652
39   TSLA                 svm_rbf  price_plus_reddit_sentiment  0.607222  0.438958  0.168263     0.087471  1.923657  0.054398

In [7]:
cv_delta = result["cv_fold_deltas"].copy()
cv_delta_summary = cv_delta.groupby(["ticker", "model_name", "feature_set_alt"], as_index=False)[["delta_balanced_accuracy", "delta_roc_auc"]].mean()
cv_delta_summary = cv_delta_summary.sort_values(["ticker", "model_name", "feature_set_alt"]).reset_index(drop=True)
cv_delta_summary

   ticker              model_name              feature_set_alt  delta_balanced_accuracy  delta_roc_auc
0    AAPL  hist_gradient_boosting             price_plus_gdelt                -0.013507      -0.037649
1    AAPL  hist_gradient_boosting     price_plus_google_trends                 0.010570       0.007886
2    AAPL  hist_gradient_boosting  price_plus_reddit_attention                 0.007747      -0.018464
3    AAPL  hist_gradient_boosting  price_plus_reddit_sentiment                -0.011155      -0.031401
4    AAPL                  logreg             price_plus_gdelt                -0.006858      -0.004220
5    AAPL                  logreg     price_plus_google_trends                 0.004543      -0.008838
6    AAPL                  logreg  price_plus_reddit_attention                -0.040005      -0.048646
7    AAPL                  logreg  price_plus_reddit_sentiment                 0.010776       0.035969
8    AAPL               mlp_small             price_plus_gdelt                -0.034325      -0.008590
9    AAPL               mlp_small     price_plus_google_trends                 0.037181       0.062075
10   AAPL               mlp_small  price_plus_reddit_attention                -0.035573      -0.033228
11   AAPL               mlp_small  price_plus_reddit_sentiment                -0.059207      -0.013955
12   AAPL           random_forest             price_plus_gdelt                -0.029079      -0.012919
13   AAPL           random_forest     price_plus_google_trends                -0.007589      -0.006384
14   AAPL           random_forest  price_plus_reddit_attention                -0.066165      -0.055966
15   AAPL           random_forest  price_plus_reddit_sentiment                 0.012095      -0.003237
16   AAPL                 svm_rbf             price_plus_gdelt                -0.022720       0.006323
17   AAPL                 svm_rbf     price_plus_google_trends                -0.018862      -0.010006
18   AAPL                 svm_rbf  price_plus_reddit_attention                -0.010967       0.014051
19   AAPL                 svm_rbf  price_plus_reddit_sentiment                -0.059609      -0.069555
20   TSLA  hist_gradient_boosting             price_plus_gdelt                 0.018588       0.023676
21   TSLA  hist_gradient_boosting     price_plus_google_trends                -0.018336       0.014452
22   TSLA  hist_gradient_boosting  price_plus_reddit_attention                -0.053726      -0.028530
23   TSLA  hist_gradient_boosting  price_plus_reddit_sentiment                -0.027277       0.011097
24   TSLA                  logreg             price_plus_gdelt                -0.015988       0.014482
25   TSLA                  logreg     price_plus_google_trends                -0.013335      -0.010555
26   TSLA                  logreg  price_plus_reddit_attention                -0.012081       0.004390
27   TSLA                  logreg  price_plus_reddit_sentiment                 0.005546       0.019010
28   TSLA               mlp_small             price_plus_gdelt                -0.007245      -0.014013
29   TSLA               mlp_small     price_plus_google_trends                 0.016003       0.013537
30   TSLA               mlp_small  price_plus_reddit_attention                -0.003112      -0.008795
31   TSLA               mlp_small  price_plus_reddit_sentiment                 0.034526       0.017901
32   TSLA           random_forest             price_plus_gdelt                 0.037767       0.011006
33   TSLA           random_forest     price_plus_google_trends                 0.003699      -0.005939
34   TSLA           random_forest  price_plus_reddit_attention                -0.030117       0.000387
35   TSLA           random_forest  price_plus_reddit_sentiment                 0.015437       0.026482
36   TSLA                 svm_rbf             price_plus_gdelt                -0.004347       0.011039
37   TSLA                 svm_rbf     price_plus_google_trends                -0.026032      -0.052670
38   TSLA                 svm_rbf  price_plus_reddit_attention                -0.008722      -0.047321
39   TSLA                 svm_rbf  price_plus_reddit_sentiment                -0.018229      -0.002947

In [8]:
thresholds = result["threshold_tuning"].copy()
thresholds = thresholds.sort_values(["ticker", "model_name", "feature_set"]).reset_index(drop=True)
thresholds

   ticker              model_name                  feature_set split_scope  decision_threshold  threshold_tuned  validation_rows  validation_balanced_accuracy
0    AAPL  hist_gradient_boosting                   price_only  final_test                0.50            False                0                           NaN
1    AAPL  hist_gradient_boosting             price_plus_gdelt  final_test                0.50            False                0                           NaN
2    AAPL  hist_gradient_boosting     price_plus_google_trends  final_test                0.50            False                0                           NaN
3    AAPL  hist_gradient_boosting  price_plus_reddit_attention  final_test                0.50            False                0                           NaN
4    AAPL  hist_gradient_boosting  price_plus_reddit_sentiment  final_test                0.50            False                0                           NaN
5    AAPL                  logreg                   price_only  final_test                0.50            False                0                           NaN
6    AAPL                  logreg             price_plus_gdelt  final_test                0.50            False                0                           NaN
7    AAPL                  logreg     price_plus_google_trends  final_test                0.50            False                0                           NaN
8    AAPL                  logreg  price_plus_reddit_attention  final_test                0.50            False                0                           NaN
9    AAPL                  logreg  price_plus_reddit_sentiment  final_test                0.50            False                0                           NaN
10   AAPL               mlp_small                   price_only  final_test                0.55             True              125                      0.597336
11   AAPL               mlp_small             price_plus_gdelt  final_test                0.60             True              125                      0.552126
12   AAPL               mlp_small     price_plus_google_trends  final_test                0.61             True              125                      0.625128
13   AAPL               mlp_small  price_plus_reddit_attention  final_test                0.68             True              125                      0.506916
14   AAPL               mlp_small  price_plus_reddit_sentiment  final_test                0.57             True              125                      0.596568
15   AAPL           random_forest                   price_only  final_test                0.50            False                0                           NaN
16   AAPL           random_forest             price_plus_gdelt  final_test                0.50            False                0                           NaN
17   AAPL           random_forest     price_plus_google_trends  final_test                0.50            False                0                           NaN
18   AAPL           random_forest  price_plus_reddit_attention  final_test                0.50            False                0                           NaN
19   AAPL           random_forest  price_plus_reddit_sentiment  final_test                0.50            False                0                           NaN
20   AAPL                 svm_rbf                   price_only  final_test                0.52             True              125                      0.512167
21   AAPL                 svm_rbf             price_plus_gdelt  final_test                0.53             True              125                      0.518058
22   AAPL                 svm_rbf     price_plus_google_trends  final_test                0.54             True              125                      0.553535
23   AAPL                 svm_rbf  price_plus_reddit_attention  final_test                0.55             True              125                      0.551230
24   AAPL                 svm_rbf  price_plus_reddit_sentiment  final_test                0.54             True              125                      0.507812
25   TSLA  hist_gradient_boosting                   price_only  final_test                0.50            False                0                           NaN
26   TSLA  hist_gradient_boosting             price_plus_gdelt  final_test                0.50            False                0                           NaN
27   TSLA  hist_gradient_boosting     price_plus_google_trends  final_test                0.50            False                0                           NaN
28   TSLA  hist_gradient_boosting  price_plus_reddit_attention  final_test                0.50            False                0                           NaN
29   TSLA  hist_gradient_boosting  price_plus_reddit_sentiment  final_test                0.50            False                0                           NaN
30   TSLA                  logreg                   price_only  final_test                0.50            False                0                           NaN
31   TSLA                  logreg             price_plus_gdelt  final_test                0.50            False                0                           NaN
32   TSLA                  logreg     price_plus_google_trends  final_test                0.50            False                0                           NaN
33   TSLA                  logreg  price_plus_reddit_attention  final_test                0.50            False                0                           NaN
34   TSLA                  logreg  price_plus_reddit_sentiment  final_test                0.50            False                0                           NaN
35   TSLA               mlp_small                   price_only  final_test                0.49             True              125                      0.550310
36   TSLA               mlp_small             price_plus_gdelt  final_test                0.68             True              125                      0.594298
37   TSLA               mlp_small     price_plus_google_trends  final_test                0.70             True              125                      0.543344
38   TSLA               mlp_small  price_plus_reddit_attention  final_test                0.70             True              125                      0.565402
39   TSLA               mlp_small  price_plus_reddit_sentiment  final_test                0.70             True              125                      0.534830
40   TSLA           random_forest                   price_only  final_test                0.50            False                0                           NaN
41   TSLA           random_forest             price_plus_gdelt  final_test                0.50            False                0                           NaN
42   TSLA           random_forest     price_plus_google_trends  final_test                0.50            False                0                           NaN
43   TSLA           random_forest  price_plus_reddit_attention  final_test                0.50            False                0                           NaN
44   TSLA           random_forest  price_plus_reddit_sentiment  final_test                0.50            False                0                           NaN
45   TSLA                 svm_rbf                   price_only  final_test                0.51             True              125                      0.525413
46   TSLA                 svm_rbf             price_plus_gdelt  final_test                0.54             True              125                      0.574303
47   TSLA                 svm_rbf     price_plus_google_trends  final_test                0.53             True              125                      0.540506
48   TSLA                 svm_rbf  price_plus_reddit_attention  final_test                0.55             True              125                      0.520382
49   TSLA                 svm_rbf  price_plus_reddit_sentiment  final_test                0.47             True              125                      0.539861